name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-build-and-test:
    strategy:
      matrix:
        go: [1.16]
        os: [ubuntu-latest]
    name: checks+go-${{ matrix.go }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37
    - name: Build
      run: go build
    - name: Tests
      run: go test
  build-and-test:
    strategy:
      matrix:
        go: [1.16]
        os: [macos-latest, windows-latest]
    name: go-${{ matrix.go }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: go build
    - name: Tests
      run: go test
